# Generated by Django 2.2 on 2020-08-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Guestbook',
        ),
    ]
